Website = "https://example.com"

[Details]
  Icon = "Icon.png"
  Name = "mayble"
  ID = "com.dubbersthehoser.mayble"
  Version = "1.0.0"
  Build = 18

[LinuxAndBSD]
  GenericName = "Book Management"
  Categories = ["Office", "Database"]
  Keywords = ["books", "office"]
