Website = "https://example.com"

[Details]
  Icon = "Icon.png"
  Name = "Mayble"
  ID = "com.dubbersthehoser.mayble"
  Version = "1.0.0"
  Build = 11

[LinuxAndBSD]
  GenericName = "Book Management"
  Categories = ["Office"]
  Keywords = ["", "web"]
